extends RefCounted

## GENERATED by build_tools/mobile_characters/build_mobile_walks.py.
## Do not edit by hand: re-run the script.
## Painted character strips for the mobile board. One entry per class
## and kind. cell and pivot are in texture px; the pivot is the ground
## point and always sits on Pawn.FOOT_PIVOT_Y (152). frames_per_tile is
## how many cells one board tile of travel spans: the no-slide value
## (frames_per_tile_no_slide) capped so the legs never cycle faster than
## MAX_LEG_RATE x the authored fps (Mauro 4 Oct 2026, natural leg speed;
## a capped class accepts a small foot slide).

const MAX_LEG_RATE := 1.6

const SPECS := {
	"bastion": {
		"walk": {
			"cell": Vector2i(186, 171),
			"pivot": Vector2i(93, 152),
			"frames": 12,
			"fps": 17.144,
			"loop": true,
			"contact": 0,
			"frames_per_tile": 9.326,
			"frames_per_tile_no_slide": 14.095,
			"scale": 0.5445,
			"source": "art/ironjaw-walk-help @ 7f65035 docs/pc/art_help/class_walk_looks/bastion/v3/frames",
		},
	},
	"gloam": {
		"walk": {
			"cell": Vector2i(188, 172),
			"pivot": Vector2i(94, 152),
			"frames": 12,
			"fps": 17.144,
			"loop": true,
			"contact": 0,
			"frames_per_tile": 9.326,
			"frames_per_tile_no_slide": 20.908,
			"scale": 0.5929,
			"source": "claude/gloam-legs @ bdf0ff3 docs/pc/art_help/class_walk_looks/gloam/v1_claude/frames",
		},
	},
	"ironjaw": {
		"walk": {
			"cell": Vector2i(160, 158),
			"pivot": Vector2i(80, 152),
			"frames": 12,
			"fps": 17.144,
			"loop": true,
			"contact": 0,
			"frames_per_tile": 9.141,
			"frames_per_tile_no_slide": 9.141,
			"scale": 1.0,
			"source": "pc/combat-look @ a0aec2e art/pc/characters/ironjaw/walk",
		},
	},
	"kestrel": {
		"walk": {
			"cell": Vector2i(162, 170),
			"pivot": Vector2i(81, 152),
			"frames": 12,
			"fps": 17.144,
			"loop": true,
			"contact": 0,
			"frames_per_tile": 9.326,
			"frames_per_tile_no_slide": 17.167,
			"scale": 0.6292,
			"source": "claude/kestrel-legs @ d08e0b7 docs/pc/art_help/class_walk_looks/kestrel/v3_claude/frames",
		},
	},
	"mender": {
		"walk": {
			"cell": Vector2i(144, 169),
			"pivot": Vector2i(72, 152),
			"frames": 12,
			"fps": 17.144,
			"loop": true,
			"contact": 0,
			"frames_per_tile": 9.326,
			"frames_per_tile_no_slide": 21.409,
			"scale": 0.6214,
			"source": "claude/mender-legs @ 08ea869 docs/pc/art_help/class_walk_looks/mender/v1_claude/frames",
		},
	},
}
